<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="MSI" failures="1" tests="12" name="Pet Tests" time="47.808" errors="0" timestamp="2021-05-03T11:59:41 IST">
  <testcase classname="com.zooplus.tests.PetTests" name="createPetTest" time="8.114"/>
  <testcase classname="com.zooplus.tests.PetTests" name="deleteInvalidPetTest" time="4.169"/>
  <testcase classname="com.zooplus.tests.PetTests" name="deletePetTest" time="3.575"/>
  <testcase classname="com.zooplus.tests.PetTests" name="getInvalidPetByIdTest" time="3.701"/>
  <testcase classname="com.zooplus.tests.PetTests" name="getPetByIdTest" time="2.769"/>
  <testcase classname="com.zooplus.tests.PetTests" name="getPetByStatusTest" time="2.506"/>
  <testcase classname="com.zooplus.tests.PetTests" name="getPetByTagsTest" time="0.98"/>
  <testcase classname="com.zooplus.tests.PetTests" name="updateInvalidPetFormDataTest" time="3.75"/>
  <testcase classname="com.zooplus.tests.PetTests" name="updateInvalidPetTest" time="2.864">
    <failure type="java.lang.AssertionError" message="expected [404] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [404] but found [200]
at com.zooplus.tests.PetTests.updateInvalidPetTest(PetTests.java:121)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- updateInvalidPetTest -->
  <testcase classname="com.zooplus.tests.PetTests" name="updatePetFormDataTest" time="6.979"/>
  <testcase classname="com.zooplus.tests.PetTests" name="updatePetTest" time="3.987"/>
  <testcase classname="com.zooplus.tests.PetTests" name="uploadImageTest" time="4.295"/>
</testsuite> <!-- Pet Tests -->
